services:
  postgres:
    image: pgvector/pgvector:pg17
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: todo
    user: "postgres:postgres"
